<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\UIComponents\NewFolder\**" />
    <Content Remove="Components\UIComponents\NewFolder\**" />
    <EmbeddedResource Remove="Components\UIComponents\NewFolder\**" />
    <None Remove="Components\UIComponents\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="ChatAgentWindow.razor.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="ChatAgentWindow.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="ChatAgentWindow.razor.css" />
    <None Remove="Components\UIComponents\UniverSheet\vtqw5j4c.iev~" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BlazorDatasheet" Version="0.11.0" />
    <PackageReference Include="MudBlazor" Version="9.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CostAnalizerApp\CostAnalizerApp.csproj" />
    <ProjectReference Include="..\Pgr.AIHub\Pgr.AIHub.csproj" />
    <ProjectReference Include="..\SharedCode\SharedCode.csproj" />
  </ItemGroup>

</Project>
