<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiedronkaParser\Integrations.csproj" />
    <ProjectReference Include="..\CostAnalizerApp.Interfaces\CostAnalizerApp.Interfaces.csproj" />
    <ProjectReference Include="..\DataSrouce\DataSource.csproj" />
    <ProjectReference Include="..\SharedCode\SharedCode.csproj" />
  </ItemGroup>

</Project>
